---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      # run once a week, by default on Monday
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
